Add subresource integrity to script tag
xurei/zxcvbn-async pull request #1
Opened 2020-02-06 18:03 UTC by mlogan

Make sure that end users can't get served a malicious zxcvbn lib that steals their passwords.

2020-02-10 22:18 UTC, mlogan commented
Please note, the Codacy check is spurious, it's because of a `!= null` check which is precisely what I mean.

2020-02-11 13:59 UTC, xurei requested changes
Thank you for this PR.

Indeed, for a security script, it is probably a good idea to add this :-P

Can you update your commit with the comment below. Once done, I'll merge it.

2020-02-11 13:59 UTC, xurei commented on index.js
> +		if (integrity != null) {
`if (integrity)` should be better here, as we probably want to check for `undefined` as well.

2020-02-11 18:48 UTC, mlogan commented on index.js
> +		if (integrity != null) {
`integrity != null` evaluates to false when `integrity` is either undefined or null, because I'm _not_ using `!==` here. `if (integrity)` would probably be fine in practice, since the user shouldn't need to be able to pass in empty strings, arrays, or false. But I still think `integrity != null` is the best option. But I'm happy to change it if you still disagree.

2020-02-13 10:09 UTC, xurei commented on index.js
> +		if (integrity != null) {
I'm really not a fan of `!=`.

You're right, it will match on `undefined` as well, but I'd rather use `typeof(integrity) !== 'undefined' || integrity !== null` instead. IMO it's better to explicitly state it instead of hiding it behind some dynamic type checking.

Both of these solutions are OK for me.

2020-02-13 18:51 UTC, mlogan commented on index.js
> +		if (integrity != null) {
Ok, changed to `if (integrity)`, please take another look.

2020-02-17 10:04 UTC, merged